config/routes.rb
Taskme::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ] do
    resources :tasks do
      resources :proposals 
    end
  end


  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get 'dashboard', to: 'dashboard#index'

  resources :reviews, :except => [:destroy]
  get 'tasks', to: 'home#tasks'

  get 'accepted', to: 'proposals#accepted' 
  get 'declined', to: 'proposals#declined' 

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :user
  belongs_to :task


  def self.for_current_user(task, current_user)
  	id = current_user.id
  	task.proposals.where("provider_id = #{id}").first
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_many :proposals

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name

  has_many :tasks
  has_many :reviews
  has_many :proposals

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.image = auth['info']['image'] || ""
      end
    end
  end

  def self.has_enough_points?(user, points)
    user.points >= points
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  # def after_sign_in_path_for(resource)
  #   dashboard_path
  # end

  # def after_sign_in_path_for(resource)
  #   dashboard_path
  # end

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  	@tasks = current_user.tasks.all
  	user_id = current_user.id
  	@proposals = Proposal.where(provider_id: user_id)
  	
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @current_user = current_user
  end

  def tasks
  	@current_user = current_user
  	@tasks = Task.all
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  #  def index
  #   @proposals = Proposal.where
  # end
  def show
  end

  def new
    @task = Task.find(params[:task_id])
    @proposal = Proposal.new
  end

  def create
    @proposal = Proposal.create(proposal_params)
    @proposal.task_id = params[:task_id]
    @proposal.provider_id = current_user.id
    if @proposal.save
      flash[:notice] = "You have successfully submitted a proposal."

      redirect_to tasks_path

    else
      flash[:alert] = "You cannot add this proposal, check the errors."
    end
  end

  def destroy
    proposal = Proposal.find(params[:id])
    proposal.destroy
    redirect_to user_task_path(current_user, params[:task_id])
  end

  def accepted

   prop = Proposal.where(id: params[:proposal]).first

   if User.has_enough_points?(current_user, prop.price)

     prop.accepted = true

     find_the_task = Task.where(id: prop.task_id).first
     find_the_task.status = "Processing"
     find_the_task.save!
     prop.save!
   else
    flash[:alert] = "Sorry, but you don't have enough points"
    redirect_to dashboard_path
   end
  end

  def declined
   prop = Proposal.where(id: params[:proposal]).first
   prop.accepted = false
   prop.save!
   redirect_to dashboard_path
  end

  # def show
  #   @task = Task.find(params[:id])
  # end

  # def edit
  #   @task = Task.find(params[:id])
  # end

  # def update
  #   @task =  Task.find(params[:id])
  #   if @task.update(task_params)
  #     flash[:notice] = "This task has been updated."
  #     redirect_to tasks_path
  #   else
  #     flash[:alert] = "Task has not been updated, see errors."
  #     render :edit
  #   end 
  # end

  # private


  def proposal_params
    params.require(:proposal).permit(:description, :price, :task_id, :provider_id, :accepted)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    # Reset the session after successful login, per
    # 2.8 Session Fixation – Countermeasures:
    # http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.where(customer_id: current_user.id)
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.create(task_params)
    @task.customer_id = current_user.id
    @task.status = "Open"

    if @task.save
      flash[:notice] = "You have successfully added a task"
      redirect_to dashboard_path(current_user)
    else
      flash[:alert] = "You cannot add this task, check the errors."
      render :new
    end
  end

  def show

    @task = Task.find(params[:id])
    @current_user = current_user
    @proposals = @task.proposals.all
  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    @task =  Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "This task has been updated."
      redirect_to user_tasks_path(current_user)
    else
      flash[:alert] = "Task has not been updated, see errors."
      render :edit
    end 
  end

  def destroy
    
    @task = Task.find(params[task_id]) 
    
      @task.destroy
      redirect_to "index"
  end

  private

  def task_params
    params.require(:task).permit(:description, :location, :status, :category, :title, :budget)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

    def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(user_id: current_user.id)
  end

  private

  def secure_params
    params.require(:user).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/proposal_helper.rb
module ProposalHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	def user_proposal?(task)
  	task.proposals.each do |proposal|
  		return true if proposal.provider_id == current_user.id
  	end
  	return false
  end
end

app/views/dashboard/_my_proposals.html.erb
<% @proposals.each do |proposal| %>
	<p>Helping <%= User.where(Task.find(proposal.task_id).customer_id).name %> </p>
	<p>Task: <%= Task.where(proposal.task_id).first.title %></p>	
<% end %>

app/views/dashboard/_my_tasks.html.erb
<h1>My Tasks</h1>

	<% @tasks.each do |task| %>
		Title: <%= task.title %> <br />
		Category: <%= task.category %> <br />
		Description: <%= task.description %> <br />
	<% end %>

	<p>You have not pending tasks. Why don't you take a look and help some one?</p>
	<%= button_to "New task", new_user_task_path(current_user), method: :get %>

<br><br>

app/views/dashboard/index.html.erb
<!-- 
<p>Available points: <%= current_user.points %></p>

<br><br>

<% render 'my_tasks' %>

<% render 'my_proposals' %> -->

<hr class="topbar"/>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="sidebar-account">   
              <div class="row ">
                <div class="col-lg-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">Faircoin</div>
                    <div class="panel-body">
                      <ul class="nav">
                        <li>
                          <!-- <a class="active" href="<%= dashboard_path %>">Dashboard</a> -->
                        </li>           
                        <li>
                          <a class="active" href="<%= new_user_task_path(current_user) %>">Ask for Help</a>
                        </li>
                        <li>
                          <a class="active" href="<%= user_tasks_path(current_user) %>">View my Requests</a>

                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>
                <div class="panel-body">

                    <div class="row">

                        <div class="col-sm-3 col-xs-6" style="border-right: 1px solid #DADADA; text-align: center; color:#27ae60;">
                            <h3 style="text-align: center; color:#27ae60;">Faircoins</h3>
                            <p style="font-size:16px;"><img src="assets/images/FC.png" width="10%" height="10%"> <b><%= current_user.points %></b></p>
                        </div>

                        <div class="col-sm-3 col-xs-6" style="border-right: 1px solid #DADADA; text-align: center;">
                            <h3 style="text-align: center;">Published requests</h3>
                            <p><%= current_user.tasks.count %></p>
                        </div>

                        <div class="col-sm-3 col-xs-6" style="border-right: 1px solid #DADADA; text-align: center;">
                            <h3 style="text-align: center;">Proposals Sent</h3>
                            <p> <%= @proposals.count %></p>
                        </div>

                        <div class="col-sm-3 col-xs-6" style="text-align: center;">
                            <h3 style="text-align: center;">Total requests</h3>
                            <p><%= @tasks.count %></p>
                        </div>

                    </div>
   
                   <!--  <div class="row">

                        <div class="col-sm-12" >
                            <h3 style="text-align: center;">Faircoin market place</h3>
                          <div class="row center" style="text-align: center; margin-top:15px;">   
                            <button type="submit" class="btn btn-primary" style="margin-left: 10px; width:200px">Buy coins</button>
                            <button type="submit" class="btn btn-primary2" style="margin-left: 10px; width:200px">Convert coins</button> 
                          </div>
                        </div>

                    </div>


                    <div class="row">

                        <div class="col-sm-12">
                            <div id="visualization"></div>
                        </div>

                    </div> -->

                </div>
            </div>
            
            <div class="panel panel-default">
                <div class="panel-heading">Aid requests & Proposals for Help</div>
                <div class="panel-body">

                    <% @tasks.each do |task| %>
           <div class="row  listing-row">
      

                <div class="col-sm-12">

                       <h3> <b>Request:</b> <%= task.title %> </h3>

                       <br>
                       <% task.proposals.each do |proposal|%>
                       <% if proposal.accepted.nil? %>
                      <div class="avatar pull-left">
                        <br>
                        <% if !(User.where(id: proposal.provider_id).first).nil? %>
                       <img margin="10px" src="<%= User.where(id: proposal.provider_id).first.image %>?&type=small">
                       <% end %>
                              </div>         

                         <h4><b>Bid</b> <br><%= proposal.price %> Faircoin<br><b>Proposal Description</b><br> <%= proposal.description %><br>
                         </h4>
                         <span class="classified_links pull-right">
                          <%= link_to "Decline", declined_path(proposal: proposal, user: current_user, task: task ), class: "btn btn-primary3 pull-right", style: "margin-left: 5px;" %>
                          <%= link_to "Accept", accepted_path(proposal: proposal, user: current_user, task: task ), class: "btn btn-primary pull-right", style: "margin-left: 5px;" %>
                      
                        <!-- <button type="submit" class="btn btn-primary3 pull-right" style="margin-left: 5px;">Reject</button> 
                        <button type="submit" class="btn btn-primary pull-right" style="margin-left: 5px;">Accept</button>    --> 
                        </span>
                        <br><br>
                         <div class="col-sm-12">
                         </div>
                         <% end %>
                       <% end %>
                    <p class="muted" style="float:right;"></p>
                    <br>
                   <!--  <p class="ad-description">
                        <strong><%= task.category %></strong>                  
                    </p> -->
                    <!-- <p> -->
                      <!-- span class=" pull-left" style="color:#27ae60;font-size:24px;">
                      <img src="assets/images/FC.png" width="20%" height="20%"> <%= task.budget %>
                      </span> -->
                      
<!--                         <span class="classified_links pull-right">
                        <button type="submit" class="btn btn-primary3 pull-right" style="margin-left: 10px;">Reject</button> 
                        <button type="submit" class="btn btn-primary pull-right" style="margin-left: 10px;">Accept</button>    
                        </span> -->
                    </p>
                </div>
            </div>

      <br />
    <hr style="display: block; height: 1px;
    border: 0; border-top: 1px solid #ddd;
    margin: 1em 0; padding: 0;">
    <% end %>


                </div>

            </div>
</div>



    </div>
</div>

<div class="footer">
    <div class="container">

        <div class="row">

            <div class="col-sm-4 col-xs-12">
                <p><strong>&copy; Faircoin 2014</strong></p>
                <p>All rights reserved</p>
            </div>          

            <div class="col-sm-8 col-xs-12">    
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron home-search" style="">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="main_description">The Social Helping Economy</h1>
                <br><br>
<br />
                                <div class="row">
                    <div class="col-sm-12" style="text-align: center">
                        <% if user_signed_in? %>
                            <a href="<%= new_user_task_path(@current_user) %>" class="btn btn-primary front-btn">I need help</a>
                        <% else %>
                            <a href="<%= signin_path %>" class="btn btn-primary front-btn">I need help</a>
                        <% end %>
                    </div>
                </div>     
                <br />      
                <div class="row">
                    <div class="col-sm-12" style="text-align: center">
                        <a href="<%= tasks_path %>" class="btn btn-primary2 front-btn">I can help</a>
                    </div>
                </div>          
                <br />

                <br />
                <div class="row">
                    <div class="col-sm-12" style="text-align: center">

                        <div id="quotes">
                            <div class="text-item" style="display: none;">Great! <strong>Vince</strong> just got his <strong>washing machine</strong> fixed by <strong>Jack</strong></div>
                            <div class="text-item" style="display: none;"><strong>Julia</strong>  <strong> passed her exam</strong> thanks to <strong>Jordan</strong></div>
                            <div class="text-item" style="display: none;">Success! <strong>Paul</strong> just saved <strong>lots of money</strong> thanks to Billy</div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">


    <div class="row directory">     
    <div class="col-sm-12 ">
                    <h2><span>What is Faircoin?</span></h2>
    </div>
    </div>
    <div class="row">

                        <div class="col-sm-4">
                            <div style="text-align: center;">
                                <img src="assets/images/icons/Faircoin.png" width="149"/>
                            </div>
                            <h2 style="text-align: center;">Virtual Economy</h2>
                            <p style="text-align: center;">Help out each other for karma points</p>
                            <br />
                            <br />
                        </div>


                        <div class="col-sm-4">
                            <div style="text-align: center;">
                                    <img src="assets/images/icons/Share.png" width="128"/>
                            </div>
                            <h2 style="text-align: center;">Share Services</h2>
                            <p style="text-align: center;">Give help in order to receive help. Making the world better, one Faircoin at a time.</p>
                            <br />
                            <br />
                        </div>

                        <div class="col-sm-4">
                            <div style="text-align: center;">
                                <img src="assets/images/icons/Crest.png" width="100"/>
                            </div>
                            <h2 style="text-align: center;">Get rewards</h2>
                            <p style="text-align: center;">Collect Faircoins and redeem them for rewards.</p>
                            <br />
                            <br />
                        </div>

    </div>  


    <div class="row">
        <div class="col-sm-12">
                <div class="row directory">
                <div class="col-sm-12 ">
                    <h2><span>They trusted in us</span></h2>
                </div>
                </div>
                
            <div id="block" style="float: left;">
        <div class="photo">
            <img src="http://i.imgur.com/L5H6rlb.png" alt="" class="photo-bg"/>
            <img src="http://i.imgur.com/j6mIQ2b.jpg" alt="" class="photo" />
        </div>
        <p class="content"><span class="laquo">&nbsp;</span>Thanks to the helping community, I was able to get my dishwasher fixed when I couldn´t afford it.<span class="raquo">&nbsp;</span></p>
        <div class="sign">
            <a href="#">Jay Hafling</a>
            <p>Freelance pineapple seller</p>
        </div>
    </div>
    
            <div id="block" style="float: right;">
        <div class="photo">
            <img src="http://i.imgur.com/L5H6rlb.png" alt="" class="photo-bg"/>
            <img src="http://static.parade.condenast.com/wp-content/uploads/2009/04/john-b-french.jpg" alt="" class="photo" />
        </div>
        <p class="content"><span class="laquo">&nbsp;</span>I love Faircoins! This community has helped me so much when I have been in a financial rut.. thanks!!<span class="raquo">&nbsp;</span></p>
        <div class="sign">
            <a href="#">Mike McDonald</a>
            <p>Freelance Pirate</p>
        </div>

        </div>
        </div>
    
    </div>
    
        </div>

<div class="footer">
    <div class="container">
        <div class="row">

            <div class="col-sm-4 col-xs-12">
                <p><strong>&copy; Faircoin 2014</strong></p>
                <p>All rights reserved</p>
            </div>          

            <div class="col-sm-8 col-xs-12">    
            </div>
        </div>
    </div>
</div>

app/views/home/tasks.html.erb
            

  <div class="container">

    <br />



    <div class="row">
       

        <div class="col-sm-12  listings">

            <div class="row listing-row" style="margin-top: -10px;">
                <div class="pull-left">
                <h1>Help Requests</h1>
                <h3>A list of things that need to be done</h3>
                </div>
                <div class="pull-right">
                    <% if user_signed_in? %>
                  <b><a href="<%= new_user_task_path(current_user) %>" class="btn btn-info" >Ask for Help</a><br /><br /></b>
                  <% end %>
                </div>
            </div>
            <% @tasks.each do |task| %>
          <b></b>
              <br />
            <div class="row  listing-row">
                            <div class="col-sm-2 avatar" align="center">
                    <img height="75" class="avatar" src="<%= User.where(id: task.customer_id).first.image %>?&type=normal">
                </div>

                <div class="col-sm-10">
                  <div class="pull-right">
                    <%= link_to "See full Description", user_task_path(current_user, task), class: "btn btn-warning" %>
                  </div>
                    <h3><%= link_to task.title, user_task_path(current_user, task) %></h3>
                    <p class="ad-description">
                      <br>  
                        <strong>By <%= User.where(id: task.customer_id).first.name %></strong>                  
                    </p>
                    <p>
                        <span class="classified_links pull-right">
                          <% if user_signed_in? %>
                            <% if task.customer_id == @current_user.id %>
                              <%= link_to "Edit Task", edit_user_task_path(current_user, task), class: "link-info underline" %> <br /><br />
                             <!--  <%= link_to "Delete", user_tasks_path(current_user, @task), method: :delete, data: { confirm: 'Are you sure?' }  %> -->
                            <% end %>
                          <% end %>
                    </p>
                </div>

            </div>
          <% end %>
        </div>

    </div>
</div><!-- Modal -->


<!-- Modal -->

<div class="footer">
    <div class="container">

        <div class="row">

            <div class="col-sm-4 col-xs-12">
                <p><strong>&copy; Faircoin 2014</strong></p>
                <p>All rights reserved</p>
            </div>          

            <div class="col-sm-8 col-xs-12">    
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a href="<%= root_path %>" title="Faircoins" id="logo">
        <img src="/assets/images/logo.png" alt="Faircoin logo" />
      </a>  
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right"> 
      <% if user_signed_in? %>
        <li><%= link_to 'Help Others', tasks_path %></li> 
        <li><%= link_to 'Dashboard', dashboard_path %></li>
        <li><%= link_to 'Logout', signout_path %></li>
        <li><img alt="" height="55" class="avatar" src="<%= current_user.image %>?&type=small" / ></li>
      <% else %>
        <li><%= link_to 'Login', signin_path %></li>
        <li><%= link_to 'Register', signin_path %></li>
      <% end %>
      </ul> 
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  
<% if user_signed_in? %>
  <li><%= link_to 'Help Others', user_tasks_path(current_user.id) %></li> 
  <!-- <li><%= link_to 'Users', users_path %></li> -->
  <li><%= link_to 'Dashboard', dashboard_path %></li>
  <li><%= link_to 'Logout', signout_path %></li>

<% else %>
  <li><%= link_to 'Login', signin_path %></li>
  <li>test</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Taskme" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Taskme" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/proposals/new.html.erb
<%= bootstrap_form_for [:user, :task, @proposal] do |f| %>
 
<hr class="topbar"/>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="sidebar-account">   
              <div class="row ">
                <div class="col-lg-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">Faircoin</div>
                    <div class="panel-body">
                      <ul class="nav">
                        <li>
                          <a class="active" href="<%= dashboard_path %>">Dashboard</a>
                        </li>           
                        <li>

                          <a class="active" href="<%= new_user_task_path %>">Ask for Help</a>
                        </li>
                        <li>
                          <a class="active" href="<%= user_tasks_path %>">View my Requests</a>

                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div class="col-sm-9">
            <form class="form-vertical" action="">
                <div class="panel panel-default">
                  <div class="panel-heading"><%= @proposal.new_record? ? 'Create' : 'Update'%> the proposal </div>
                    <div class="panel-body">
                      <div class="row">  
                        <div class="col-sm-12 "  >
                          <div class="form-group">
                            <div class="row">
                              <div class="col-sm-2" style="margin-top: 10px;">
                              </div>
                               <div class="col-sm-12">
                               
                                <%= f.number_field :price, label: "How many FairCoins will take to make you do it?", placeholder: "e.g. 1000", html: { class: "form-control col-sm-12" } %>
                              </div>
                              <div class="col-sm-2" style="margin-top: 10px;">
                                <!-- <label>Description</label> -->
                              </div>
							 <div class="col-sm-12">
							 	
                                <%= f.text_field :description, label: "Any comments?", placeholder: "e.g. Would you need to paint as well?", html: { class: "form-control col-sm-12" }, rows: 8 %>
                              </div>
                              <div class="col-sm-2" style="margin-top: 10px;">
                                <!-- <label>Description</label> -->
                              </div>	
								
                              <div class="col-sm-6">

                                     <%= f.submit(@proposal.new_record? ? 'Create' : 'Update') %> 
                                </div> 
                                
                            </div>
                          </div>      
                        </div>      
                      </div>      
                    </div>      
                  </div>

                  <% end %>



            </div>




        </div>
    </div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1>Aid Requests</h1>
      </div>
      <% if user_signed_in? %>
      <b><a href="<%= new_user_task_path(current_user) %>">Ask for help!</a><br /><br /></b>
      <% end %>
        <% @tasks.each do |task| %>
          <b></b>
          <%= link_to task.title, user_task_path(current_user, task) %><br />
          <% if user_signed_in? %>
            <% if task.customer_id == @current_user.id %>
              <%= link_to "Edit Task", edit_user_task_path(current_user, task) %> <br /><br />
              <%= link_to "Delete", user_tasks_path(current_user, @task), method: :delete, data: { confirm: 'Are you sure?' }  %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render 'task_form' %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>